import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "../context/AuthProvider";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import PrimeSSRProvider from "./prime-ssr-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PrimeSSRProvider>
          <AuthProvider>
            <div className="flex min-h-screen flex-col">
              <Navbar />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </AuthProvider>
        </PrimeSSRProvider>
      </body>
    </html>
  );
}
